# Generated by Django 2.0.13 on 2020-11-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
